#!/usr/bin/env python
# Usage: activefolders push <destination> <username> <keyfile>
# Summary: Push current directory to the destination
# Help: Upload the directory contents, then initiate a transfer to the destination


import requests
from requests.auth import HTTPBasicAuth as rauth
import sys
import os
import os.path
import json
import time

def read_config(path):
    try:
        with open(path) as f:
            return json.load(f)
    except (IOError,ValueError):
        return None

# Uploader function for os.path.walk
def upload(ext, dirname, names):
    for name in names:
        if name is '.activefolders':
            continue
        sourcepath = os.path.join(dirname, name)
        destpath = folder_url + "/files" + sourcepath[1:]
        if not os.path.isdir(sourcepath):
            with open(sourcepath) as f:
                r = requests.put(destpath, data=f.read(), verify=False, auth=auth)
                print("\t"+sourcepath)


# Get config
config = read_config(os.path.expanduser("~/.activefolders"))
if os.path.exists("./.activefolders"):
    config = read_config("./.activefolders")

if config:
    url = config['url']
    auth = rauth(config['secret'], None)
else:
    print("No connection found, please run `connect` first")
    sys.exit(0)

if config.get('folder'):
    print("This directory already has been uploaded into folder " + config['folder'])
    sys.exit(0)

# Parse arguments
try:
    destination, user, keyfile  = sys.argv[1:4]
    with open(keyfile) as f:
        key = f.read()
except ValueError:
    print("Provide all three arguments please: destination, username, keyfile")
    sys.exit(0)


r = requests.post(url + "/create_folder", verify=False, auth=auth)
if r.status_code / 100 is 2:
    folder = r.text
else:
    print "Error creating folder, code", r.status_code
    sys.exit(r.status_code)

folder_url = url + "/folders/" + folder


# Upload the current directory
print("Uploading to %s" % folder)
time.sleep(1)
os.path.walk('.', upload, None)

# Provide a destination to send files to
req = {
    'credentials':{
        'user': user,
        'private_key':key
    },
    'check_for_results': True
}

try:
    results_destination, results_user, results_keyfile = sys.argv[4:7]
    with open(results_keyfile) as f:
        key = f.read()
    req['results_destination'] = results_destination
    req['results_credentials'] = {
        'user': results_user,
        'private_key': key
    }
except ValueError:
    pass

params = {'dst':destination}
headers = {'Content-Type':"application/json"}
r = requests.post(folder_url+'/destinations', data=json.dumps(req), params=params, headers=headers, verify=False, auth=auth)

# Start transfer
requests.post(folder_url+'/start_transfers', verify=False, auth=auth)

# Save cache
config['folder'] = folder
config['destination'] = destination
with open("./.activefolders", "w") as f:
    json.dump(config, f, indent=4)
